import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Montserrat } from "next/font/google";
import NextTopLoader from "nextjs-toploader";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-montserrat",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <NextTopLoader  
     color="#2299DD"
     initialPosition={0.08}
     crawlSpeed={200}
     height={3}
     crawl={true}
     showSpinner={true}
     easing="ease"
     speed={200}
     shadow="0 0 10px #2299DD,0 0 5px #2299DD"
     template='<div class="bar" role="bar"><div class="peg"></div></div> 
     <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
     zIndex={1600}
     showAtBottom={false}
        />
        {children}
      </body>
    </html>
  );
}
